name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']  # or your default branch
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        env:
          BASE_PATH: '/your-repo-name'
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1